global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheusJob'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090'] #Servidor prometheus
  - job_name: 'ticket-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'Ticket Service'
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: 'User Service'
  - job_name: 'team-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
        labels:
          application: 'Team Service'
